name: string_to_color
description: convert string to color
version: 1.0.2
homepage: https://github.com/hiranthaR/string_to_color

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
